snowflake:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: _account_

      # User/password auth
      user: _user_
      password: _password_

      role: _role_
      database: _db_
      warehouse: _wh_
      schema: _schema_
      threads: 6
      client_session_keep_alive: False


      # optional
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false 
      retry_all: False  # default: false