snowflake:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: ${SNOWFLAKE_ACCOUNT}

      # User/password auth
      user: ${SNOWFLAKE_USER}
      password: ${SNOWFLAKE_PASSWORD}

      role: ${SNOWFLAKE_ROLE}
      database: ${SNOWFLAKE_DB}
      warehouse: ${SNOWFLAKE_WH}
      schema: ${SNOWFLAKE_SCHEMA}
      threads: 6
      client_session_keep_alive: False


      # optional
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false 
      retry_all: False  # default: false