snowflake:
  outputs:
    dev:
      account: ${SNOWFLAKE_ACCOUNT}
      database: ${SNOWFLAKE_DB}
      password: ${SNOWFLAKE_PASSWORD}
      role: ${SNOWFLAKE_ROLE}
      schema: ${SNOWFLAKE_SCHEMA}
      threads: 4
      type: snowflake
      user: ${SNOWFLAKE_USER}
      warehouse: ${SNOWFLAKE_WH}
  target: dev