snowflake:
  outputs:
    dev:
      account: _account_
      database: _db_
      password: _password_
      role: _role_
      schema: _schema_
      threads: 4
      type: snowflake
      user: _user_
      warehouse: _wh_
  target: dev